server:
  port: ${PORT:8081}
  shutdown: graceful

spring:
  application:
    name: vyroflix-platform
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  lifecycle:
    timeout-per-shutdown-phase: 20s

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
